version: '2.4'
services:
  db:
    image: mysql
    container_name: mysql_LibraryProject
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - project_Library_data:/var/lib/mysql

volumes:
  project_Library_data: